# Generated by Django 2.1.1 on 2018-09-28 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CaiPiaoInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cp_date', models.CharField(max_length=255)),
                ('cp_num', models.CharField(max_length=255)),
                ('cp_red_1', models.IntegerField()),
                ('cp_red_2', models.IntegerField()),
                ('cp_red_3', models.IntegerField()),
                ('cp_red_4', models.IntegerField()),
                ('cp_red_5', models.IntegerField()),
                ('cp_red_6', models.IntegerField()),
                ('cp_blue_7', models.IntegerField()),
            ],
        ),
    ]
